name: Build macOS App

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  build-macos:
    runs-on: macos-14

    steps:
      - name: Check out repository
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version-file: go.mod

      - name: Check formatting
        run: if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then exit 1; fi

      - name: Vet
        run: go vet ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v9

      - name: Install Fyne CLI
        run: go install fyne.io/tools/cmd/fyne@latest

      - name: Build Go code
        run: go build ./...

      - name: Package app bundle
        run: ~/go/bin/fyne package -os darwin -name MicroView

      - name: Zip app bundle
        run: ditto -c -k --sequesterRsrc --keepParent MicroView.app MicroView-macos.zip

      - name: Upload app artifact
        uses: actions/upload-artifact@v7
        with:
          name: MicroView-macos
          path: |
            MicroView.app
            MicroView-macos.zip
